# Generated by Django 5.0.2 on 2024-11-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeechRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('selected_voice', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('video_with_audio', models.FileField(upload_to='processed_videos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
