# Generated by Django 5.0.2 on 2024-11-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeechRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('selected_voice', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='parametre',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='user',
        ),
        migrations.DeleteModel(
            name='Parametre_vocal',
        ),
        migrations.DeleteModel(
            name='Contenu',
        ),
    ]
